name: NATS Server Long-Running Tests

on:
  workflow_dispatch:

concurrency:
  # At most one of these workflow per ref running
  group: ${{ github.workflow }}-${{ github.ref }}
  # New one cancels in-progress one
  cancel-in-progress: true

jobs:
  long-js-cluster:
    name: Long-running JetStream Cluster tests
    runs-on: ${{ vars.GHA_WORKER_LARGE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          # Use go version from go.mod
          # go-version-file: "go.mod"
          # Use latest stable go version
          go-version: stable

      - name: Run tests
        run: go test -race -v -run='^TestLong.*' ./server -tags=include_js_cluster_long_running_tests -count=1 -vet=off -timeout=60m -shuffle on -p 1  -failfast
